# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-27 13:29
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FdsMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_md5', models.CharField(max_length=100, verbose_name='md5值')),
                ('upload_ip', models.GenericIPAddressField(verbose_name='客户端上传ip')),
                ('fds_storage_path', models.FilePathField(max_length=200, path='/group1/M00', verbose_name='fds存储位置')),
                ('group_name', models.CharField(max_length=100, verbose_name='上传群主')),
                ('fds_add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='fds添加时间')),
                ('upload_status', models.CharField(max_length=100, verbose_name='上传fds状态')),
                ('fds_size', models.FloatField(default=0, verbose_name='fds文件大小')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
            },
        ),
        migrations.CreateModel(
            name='UploadMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('file_md5', models.CharField(max_length=100, verbose_name='md5值')),
                ('file_path', models.ImageField(upload_to='', verbose_name='文件位置')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('file_type', models.CharField(max_length=100, verbose_name='文件类型')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='文件创建时间')),
                ('upload_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='上传时间')),
                ('space', models.CharField(default=None, max_length=100, verbose_name='空间名')),
                ('file_desc', DjangoUeditor.models.UEditorField(default='', verbose_name='内容')),
                ('file_fds_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='md5', to='media_files.FdsMessage', verbose_name='md5值')),
            ],
            options={
                'verbose_name': '上传信息',
                'verbose_name_plural': '上传信息',
                'db_table': 'upload_message',
            },
        ),
    ]
