# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-29 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0002_auto_20181129_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmessage',
            name='file_path',
            field=models.FileField(upload_to='201811/', verbose_name='文件位置'),
        ),
    ]
