# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-30 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0003_auto_20181129_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadmessage',
            name='file_path',
            field=models.ImageField(upload_to='', verbose_name='文件位置'),
        ),
    ]
