# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0004_auto_20181220_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagesmessage',
            name='fds_path',
            field=models.CharField(max_length=255, verbose_name='上传图片地址'),
        ),
    ]
