# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-20 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_auto_20181220_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimagesmessage',
            name='fds_path',
            field=models.ImageField(blank=True, upload_to='', verbose_name='上传图片地址'),
        ),
    ]
