# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-01 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_files', '0005_auto_20181201_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
