# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-15 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostScanInifo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=64, verbose_name='主机IP信息')),
                ('login_port', models.CharField(max_length=32, null=True, verbose_name='登录的端口')),
                ('login_user', models.CharField(max_length=32, null=True, verbose_name='登录的用户')),
                ('login_passwd', models.CharField(default='', max_length=64, null=True, verbose_name='登录的密码')),
                ('login_status', models.IntegerField(default=0, verbose_name='0-登录失败,1-登录成功')),
                ('host_type', models.CharField(default='', max_length=256, null=True, verbose_name='主机系统类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '初始化扫描信息表',
                'verbose_name_plural': '初始化扫描信息表',
                'db_table': 'hosts_scan_inifo',
            },
        ),
    ]
