# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-22 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerifyCode',
            new_name='EmailVerifyCode',
        ),
    ]
